### PR TITLE
Code Cleaning

### PR DESCRIPTION
**Pull request by aaranmcguire**
I have removed some code that was not used ready for me to create new features.

Let me know if you have any questions.

(Code has been tested and works perfectly)

### CODE REVIEW

**Comment by aaranmcguire** [comment]
Why did you revert the merge?

**Comment by havingar** [comment]
I had to revert it and then re-merge due to conflicts.Thanks for your help. Let me know the new features and can merge in as I don't have a huge amount of time to work on this any more. Will add you to the maintainers in Moodle.org if you like?

**Comment by aaranmcguire** [comment]
From what I can see its not been re-merged.. 

The features I'm hoping to add is have one location of all the GSB calculation (not on the block and report), process GSB via cron, provide tips to teachers on how to bring their courses to the next level.

If you have any ideas, let me know and I will see I could implement them.

As for adding me to the maintainers, I don't mind, it's up to you.

**Comment by havingar** [comment]
There is a problem with your code I believe. Can you turn on Auto Medals and see if it works for you. Once this is fixed I will remerge. Thanks

**Pull request merged**
